export const orders = [
  {
    id: 1,
    adminId: 'api',
    products: [
      {
        title: 'Reminders of Him',
        category: 'Romance',
        price: 38,
        quantity: 1,
        photo: 'https://m.media-amazon.com/images/I/41EiBLxybSL.jpg',
      },
    ],
    total_price: 250,
    created_at: '2022-2-5',
    user_id: '1',
    user: 'Chelsey_Dietrich',
    order_number: '1125',
    shipping_address: {
      street: 'Victor Plains',
      suite: 'Suite 879',
      city: 'Wisokyburgh',
      zipcode: '90566-7771',
    },
    status: 'pending',
  },
  {
    id: 2,
    adminId: 'api',
    products: [
      {
        title: 'Reminders of Him',
        category: 'Romance',
        price: 38,
        quantity: 1,
        photo: 'https://m.media-amazon.com/images/I/41EiBLxybSL.jpg',
      },
      {
        title: 'Apples Never Fall',
        category: 'Fantasy',
        price: 5,
        quantity: 1,
        photo: 'https://images-na.ssl-images-amazon.com/images/I/41c96JYqF8L._SX327_BO1,204,203,200_.jpg',
      },
    ],
    total_price: 250,
    created_at: '2022-2-9',
    user: 'Ervin_Howell',
    order_number: '1126',
    shipping_address: {
      street: 'Kulas Light',
      suite: 'Apt. 556',
      city: 'Gwenborough',
      zipcode: '92998-3874',
    },
    status: 'pending',
  },
  {
    id: 3,
    adminId: 'api',
    products: [
      {
        title: 'Reminders of Him',
        category: 'Romance',
        price: 38,
        quantity: 1,
        photo: 'https://m.media-amazon.com/images/I/41EiBLxybSL.jpg',
      },
      {
        title: 'Greenlights',
        category: 'Biographie',
        price: 17,
        quantity: 1,
        photo: 'https://images-na.ssl-images-amazon.com/images/I/51midYhXu8L._SY291_BO1,204,203,200_QL40_FMwebp_.jpg',
      },
      {
        title: 'Kingdom of the Cursed',
        category: 'Fantasy',
        price: 6,
        quantity: 1,
        photo: 'https://m.media-amazon.com/images/I/41EiBLxybSL.jpg',
      },
    ],
    total_price: 250,
    created_at: '2022-2-1',
    user: 'Clementine_Bauch',
    user_id: '1',
    order_number: '1133',
    shipping_address: {
      street: 'Douglas Extension',
      suite: 'Suite 847',
      city: 'McKenziehaven',
      zipcode: '59590-4157',
    },
    status: 'pending',
  },
  {
    id: 4,
    adminId: 'api',
    products: [
      {
        title: 'Greenlights',
        author: 'Matthew McConaughey',
        category: 'Biographie',
        price: 17,
        quantity: 1,
        photo: 'https://images-na.ssl-images-amazon.com/images/I/51midYhXu8L._SY291_BO1,204,203,200_QL40_FMwebp_.jpg',
      },
      {
        title: 'Kingdom of the Cursed',
        category: 'Fantasy',
        price: 6,
        quantity: 1,
        photo: 'https://m.media-amazon.com/images/I/41EiBLxybSL.jpg',
      },
    ],
    total_price: 250,
    created_at: '2022-2-2',
    user: 'Patricia_Lebsack',
    order_number: '1128',
    shipping_address: {
      street: 'Hoeger Mall',
      suite: 'Apt. 692',
      city: 'South Elvis',
      zipcode: '53919-4257',
    },
    status: 'pending',
  },
];
